services:
  db:
    image: mysql
    container_name: MySQL
    command: ['mysqld', "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci"]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpMyAdmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 120M
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  db-data:
